version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nestjs_react_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
